{
 "title": "MongoDB Driver",
 "tags": [ "MongoDB" ],
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "instance",
    "label": "Instance",
    "query": {
     "query": "label_values(mongodb_driver_commands_seconds_sum{},instance)"
    }
   },
   {
    "name": "collection",
    "label": "Collection",
    "query": {
     "query": "label_values(mongodb_driver_commands_seconds_sum{instance=~'$instance'},collection)"
    }
   },
   {
    "name": "command",
    "label": "Command",
    "query": {
     "query": "label_values(mongodb_driver_commands_seconds_sum{instance=~'$instance'},command)"
    }
   },
   {
    "name": "server_address_copy",
    "label": "Server",
    "query": {
     "query": "label_values(mongodb_driver_commands_seconds_sum{},server_address)"
    }
   },
   {
    "name": "server_address",
    "label": "Server",
    "query": {
     "query": "label_values(mongodb_driver_pool_min,server_address)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Connections", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Active Connections",
   "type": "timeseries",
   "description": "The number of connections that are currently in use.",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(irate(mongodb_driver_pool_checkedout{instance=~\"$instance\"}[$__rate_interval])) by (instance, server_address)",
     "legendFormat": "{{instance}} - {{server_address}}"
    }
   ]
  },
  {
   "title": "Connection Pool Usage",
   "type": "timeseries",
   "description": "Current size of the connection pool, including idle and and in-use members.",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(mongodb_driver_pool_size{instance=~\"$instance\", server_address=~\"$server_address\"}) by (instance, server_address)",
     "legendFormat": "{{instance}} - {{server_address}}"
    }
   ]
  },
  {
   "title": "Connection Pool Utilization",
   "type": "timeseries",
   "description": "Current size of the connection pool, including idle and and in-use members.",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(mongodb_driver_pool_size{instance=~\"$instance\", server_address=~\"$server_address\"}) by (instance, server_address) / sum(mongodb_driver_pool_max{instance=~\"$instance\", server_address=~\"$server_address\"}) by (instance, server_address)",
     "legendFormat": "{{instance}} - {{server_address}}"
    }
   ]
  },
  {
   "title": "Connection Wait Queue",
   "type": "timeseries",
   "description": "The current size of the wait queue for a connection from the pool.",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(mongodb_driver_pool_waitqueuesize{instance=~\"$instance\", server_address=~\"$server_address\"}) by (instance, server_address)",
     "legendFormat": "{{instance}} - {{server_address}}"
    }
   ]
  },
  {
   "title": "Connection Pool Min",
   "type": "timeseries",
   "description": "Minimum size of the connection pool.",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(mongodb_driver_pool_min{instance=~\"$instance\", server_address=~\"$server_address\"}) by (instance, server_address)",
     "legendFormat": "{{instance}} - {{server_address}}"
    }
   ]
  },
  {
   "title": "Connection Pool Max",
   "type": "timeseries",
   "description": "Maximum size of the connection pool.",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(mongodb_driver_pool_max{instance=~\"$instance\", server_address=~\"$server_address\"}) by (instance, server_address)",
     "legendFormat": "{{instance}} - {{server_address}}"
    }
   ]
  },
  { "title": "Commands", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 } },
  {
   "title": "Commands Latency By Command",
   "type": "timeseries",
   "description": "Average command execution latency.",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum(rate(mongodb_driver_commands_seconds_sum{instance=~\"$instance\", collection=~\"$collection\", command=~\"$command\"}[$__rate_interval])) by (instance, collection, command) / sum(rate(mongodb_driver_commands_seconds_count{instance=~\"$instance\", collection=~\"$collection\", command=~\"$command\"}[$__rate_interval])) by (instance, collection, command)",
     "legendFormat": "{{instance}} - {{collection}} - {{command}}"
    }
   ]
  },
  {
   "title": "Commands Rate By Command",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(rate(mongodb_driver_commands_seconds_count{instance=~\"$instance\", collection=~\"$collection\", command=~\"$command\"}[$__rate_interval])) by (instance, collection, command)",
     "legendFormat": "{{instance}} - {{collection}} - {{command}}"
    }
   ]
  },
  {
   "title": "Erroneous Commands Rate By Command",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(rate(mongodb_driver_commands_seconds_count{instance=~\"$instance\", collection=~\"$collection\", command=~\"$command\", status=\"FAILED\"}[$__rate_interval])) by (instance, collection, command)",
     "legendFormat": "{{instance}} - {{collection}} - {{command}}"
    }
   ]
  },
  {
   "title": "Commands",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(mongodb_driver_commands_seconds_count{instance=~\"$instance\", collection=~\"$collection\", command=~\"$command\"}) by (instance, collection, command)",
     "legendFormat": "{{instance}} - {{collection}} - {{command}}"
    }
   ]
  },
  {
   "title": "Erroneous Commands",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(mongodb_driver_commands_seconds_count{instance=~\"$instance\", collection=~\"$collection\", command=~\"$command\", status=\"FAILED\"}) by (instance, collection, command)",
     "legendFormat": "{{instance}} - {{collection}} - {{command}}"
    }
   ]
  }
 ]
}